// Builds the skill's generated files from the extension sources:
//   skill/code-tour/scripts/validate-tour.mjs  (bundled validator, runs with plain node)
//   skill/code-tour/schema/tour.schema.json    (copy of the canonical schema)
// Run with `npm run build:skill`. Never edit the outputs by hand.
import { build } from "esbuild";
import { copyFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const extensionDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const skillDir = join(extensionDir, "..", "skill", "code-tour");

mkdirSync(join(skillDir, "scripts"), { recursive: true });
mkdirSync(join(skillDir, "schema"), { recursive: true });

await build({
  entryPoints: [join(extensionDir, "skill-src", "validate-tour.ts")],
  outfile: join(skillDir, "scripts", "validate-tour.mjs"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  legalComments: "none",
  banner: {
    js: "// GENERATED by extension/scripts/build-skill.mjs from extension/skill-src and extension/src. Do not edit.",
  },
  logLevel: "warning",
});

copyFileSync(join(extensionDir, "schema", "tour.schema.json"), join(skillDir, "schema", "tour.schema.json"));
console.log(`Built ${join(skillDir, "scripts", "validate-tour.mjs")}`);
